apiVersion: v1
kind: Service
metadata:
  name: node-webserver
  labels:
    app: node-webserver
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6005
  selector:
    app: node-webserver
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-webserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-webserver
    spec:
      containers:
        - name: node-webserver
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 6005
